import type { vars as sourceVars } from './vars';

export type DocsVars = typeof sourceVars;

const GENERATED_FILE_HEADER =
  '{/* This file is generated by `pnpm vars:build`. Do not edit directly. */}';

const renderComponentExports = (docsVars: DocsVars): string => {
  const products = JSON.stringify(docsVars.products, null, 2);
  const installCommands = JSON.stringify(docsVars.install, null, 2);
  const supportEmail = JSON.stringify(docsVars.emails.support);
  const securityEmail = JSON.stringify(docsVars.emails.security);
  const discordUrl = JSON.stringify(docsVars.urls.discord);
  const docsUrl = JSON.stringify(docsVars.urls.docs);
  const githubRepos = JSON.stringify(docsVars.urls.github.repo, null, 2);

  return `export function ProductName({ variant }) {
  const products = ${products};

  return products[variant];
}

export function InstallCommand({ platform }) {
  const installCommands = ${installCommands};

  return installCommands[platform];
}

export function SupportLink({ children }) {
  const supportEmail = ${supportEmail};
  const href = \`mailto:\${supportEmail}\`;

  return <a href={href}>{children ?? supportEmail}</a>;
}

export function SecurityLink({ children }) {
  const securityEmail = ${securityEmail};
  const href = \`mailto:\${securityEmail}\`;

  return <a href={href}>{children ?? securityEmail}</a>;
}

export function DiscordInvite({ children }) {
  const discordUrl = ${discordUrl};

  return (
    <a href={discordUrl} target="_blank" rel="noreferrer">
      {children ?? discordUrl}
    </a>
  );
}

export function DocsURL({ path = '', children }) {
  const docsUrl = ${docsUrl};
  const normalizedPath = path && path.startsWith('/') ? path : \`/\${path}\`;
  const href = path ? \`\${docsUrl}\${normalizedPath}\` : docsUrl;

  return <a href={href}>{children ?? href}</a>;
}

export function GithubRepo({ repo, children }) {
  const githubRepos = ${githubRepos};
  const href = githubRepos[repo];

  return (
    <a href={href} target="_blank" rel="noreferrer">
      {children ?? href}
    </a>
  );
}`;
};

export const renderVarsMdx = (docsVars: DocsVars): string => {
  const serializedVars = JSON.stringify(docsVars, null, 2);

  return `${GENERATED_FILE_HEADER}

export const vars = ${serializedVars};

${renderComponentExports(docsVars)}
`;
};
