import type { vars as sourceVars } from './vars';

export type DocsVars = typeof sourceVars;

const GENERATED_FILE_HEADER =
  '{/* This file is generated by `pnpm vars:build`. Do not edit directly. */}';

const COMPONENT_EXPORTS = `export function ProductName({ variant }) {
  return vars.products[variant];
}

export function InstallCommand({ platform }) {
  return (
    <pre>
      <code>{vars.install[platform]}</code>
    </pre>
  );
}

export function SupportLink({ children }) {
  return (
    <a href={\`mailto:\${vars.emails.support}\`}>
      {children ?? vars.emails.support}
    </a>
  );
}

export function SecurityLink({ children }) {
  return (
    <a href={\`mailto:\${vars.emails.security}\`}>
      {children ?? vars.emails.security}
    </a>
  );
}

export function DiscordInvite({ children }) {
  return (
    <a href={vars.urls.discord} target="_blank" rel="noreferrer">
      {children ?? vars.urls.discord}
    </a>
  );
}

export function DocsURL({ path = '', children }) {
  const normalizedPath = path && path.startsWith('/') ? path : \`/\${path}\`;
  const href = path ? \`\${vars.urls.docs}\${normalizedPath}\` : vars.urls.docs;

  return <a href={href}>{children ?? href}</a>;
}

export function GithubRepo({ repo, children }) {
  const href = vars.urls.github.repo[repo];

  return (
    <a href={href} target="_blank" rel="noreferrer">
      {children ?? href}
    </a>
  );
}`;

export const renderVarsMdx = (docsVars: DocsVars): string => {
  const serializedVars = JSON.stringify(docsVars, null, 2);

  return `${GENERATED_FILE_HEADER}

export const vars = ${serializedVars};

${COMPONENT_EXPORTS}
`;
};
